baseURL = "https://leobugeja.com"
languageCode = "en-gb"
title = "Leo's blog"
min_version = "0.84.0"
[permalinks]
	posts = "/:slug/"
[markup]
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		lineNos = false
		lineNumbersInTable = false
		noClasses = true
		style = "friendly" # monokailight, friendly, emacs, tango, manni
